apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-{{ .Release.Name }}
  labels:
    app: chat-app-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat-app-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: chat-app-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
