apiVersion: v1
kind: Service
metadata:
  name: chat-app-{{ .Release.Name }}
  labels:
    app: chat-app-{{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 12345
      targetPort: 12345
      protocol: TCP
  selector:
    app: chat-app-{{ .Release.Name }}
