apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chat-app
  name: chat-app
spec:
  ports:
  - port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: chat-app
  type: NodePort
status:
  loadBalancer: {}
